services:
  # Broker MQTT de campo (Capa Edge/Fog)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: factory_mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
    networks:
      - factory-network

  # Procesador Analítico Local (Capa Fog)
  fog-processor:
    image: ariegd/fog-processor:latest
    container_name: factory_fog_processor
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_HOST=mqtt-broker
      - CLOUD_API_URL=http://34.175.14.105:8000/predict
    networks:
      - factory-network

networks:
  factory-network:
    driver: bridge

volumes:
  mosquitto_data:
