name: CI/CD Industrial Automation

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-push-fog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Compilar y subir imagen del procesador Fog
      uses: docker/build-push-action@v5
      with:
        context: ./src/fog-processor   # Asegúrate de que esta sea la ruta correcta a la carpeta fog-processor
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/fog-processor:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/fog-processor:${{ github.sha }}
